# Generated by Django 3.2.9 on 2021-12-11 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_prediction_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bettoreturn',
            old_name='to_return',
            new_name='payoff',
        ),
        migrations.AddField(
            model_name='bettoreturn',
            name='result_one_win',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettoreturn',
            name='result_thr_win',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettoreturn',
            name='result_two_win',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettoreturn',
            name='win',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettoreturn',
            name='win_show',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bettoreturn',
            name='bet',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='bettoreturn',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bettoreturn',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
